FROM node:18-alpine

WORKDIR /app

ARG NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3005
RUN npm run build

CMD ["npm", "start"]